ALTER TABLE "hang_calendar" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "hang_calendar" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "hang_calendar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "hang_calendar_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "hang_calendar" DROP COLUMN IF EXISTS "name";